# Generated by Django 5.0.1 on 2024-03-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=20, null=True)),
                ('price', models.IntegerField(null=True)),
                ('ratings', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('discount', models.IntegerField()),
                ('availability', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=20, null=True)),
                ('ownerName', models.CharField(max_length=20, null=True)),
                ('rollNo', models.IntegerField(max_length=15, null=True)),
                ('ownerEmail', models.EmailField(max_length=30)),
                ('accessCode', models.CharField(max_length=10)),
            ],
        ),
    ]
